from building import *
Import('rtconfig')

cwd = GetCurrentDir()
src	= Glob('*.c')
path = [cwd]

group = DefineGroup('Drivers', src, depend = ['RT_USING_SPI_BITOPS_DEMO'], CPPPATH = path)

Return('group')