from building import *
Import('rtconfig')

cwd = GetCurrentDir()
src	= Glob('*.c')
path = [cwd]

group = DefineGroup('DeviceDrivers', src, depend = ['RT_USING_SPI_BITOPS'], CPPPATH = path)

Return('group')